package primero;
// Generated 06-Feb-2019 23:40:45 by Hibernate Tools 5.2.11.Final

/**
 * DepartId generated by hbm2java
 */
public class DepartId implements java.io.Serializable {

	private Integer deptNo;
	private String dnombre;
	private String loc;

	public DepartId() {
	}

	public DepartId(Integer deptNo, String dnombre, String loc) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
	}

	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartId))
			return false;
		DepartId castOther = (DepartId) other;

		return ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null
				&& castOther.getDeptNo() != null && this.getDeptNo().equals(castOther.getDeptNo())))
				&& ((this.getDnombre() == castOther.getDnombre()) || (this.getDnombre() != null
						&& castOther.getDnombre() != null && this.getDnombre().equals(castOther.getDnombre())))
				&& ((this.getLoc() == castOther.getLoc()) || (this.getLoc() != null && castOther.getLoc() != null
						&& this.getLoc().equals(castOther.getLoc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		result = 37 * result + (getDnombre() == null ? 0 : this.getDnombre().hashCode());
		result = 37 * result + (getLoc() == null ? 0 : this.getLoc().hashCode());
		return result;
	}

}
